# Better Shulker Boxes - By Rektb
# PLEASE SEE https://github.com/lMartin3/BetterShulkerBoxes/blob/master/src/main/resources/config.yml for an example config.yml
# PERMISSIONS:
# bettershulkerboxes.*: Grants all permissions (Recommended for admins)
# bettershulkerboxes.use.*; Grants all permissions (Recommended for users)
# bettershulkerboxes.use: Allows players to open shulkerboxes in both ways UNLESS rightclick_requires_permission is set to true
# bettershulkerboxes.use.rightclick: Allows players to open shulkerboxes by rightclicking them in the inventory (rightclick_requires_permission doesn't matter)
# bettershulkerboxes.bypasscooldown: Allows players to bypass the cooldown (Recommended for exclusive ranks)
# bettershulkerboxes.updatenotify: Allows players to receive notification about new versions. (Recommended for admins)
# bettershulkerboxes.reload: Allows players to reload the config. (Recommended for admins)

version: 2.9.0 # Do not touch

prefix: '&8[&3BSB&8] ' # Prefix of the messages in chat
inventory_name: '&7Shulkerbox' # Name of the inventory (can use %itemname% to use item's name)
open_msg: '&eOpening shulkerbox...' # Put 'none' to disable (with the quotes)
close_msg: '&eClosing shulkerbox...' # Put 'none' to disable (with the quotes)
no_permission_msg: '&cPermission denied' # Message that players will get when they haven't got enough permissions
cooldown_msg: '&cYou have to wait until you can use this again' # This is sent to the player if he tries to open the shulkerbox but the cooldown hasn't finished
config_reload_msg: '&bConfiguration reloaded successfully' # Message sent to admin/console when the plugin configuration is reloaded successfully
config_reload_error_msg: '&cThere is an error in the configuration, see the console for details' # Like above but not good

cooldown: 5 # [Integer] In ms (milliseconds) the time players have to wait open another shulkerbox after opening one.
open_sound: 'BLOCK_SHULKER_BOX_OPEN' # [String (sound)] Like messages, put 'none' (with the quotes) to disable
close_sound: 'BLOCK_SHULKER_BOX_CLOSE' # [String (sound)] Like messages, put 'none' (with the quotes) to disable
cooldown_enabled: true # [Boolean] To enable or not the cooldown (Recommended)
requires_permission: true # [Boolean] Do players require permission to open shulkerboxes using the plugin? (Recommended)
enable_read_only: false # [Boolean] Enable 'read-only' mode, allowing players to see contents but not to modify them. They will have to place the shulkerbox. (Not recommended)
enable_rclick_air_open: true # [Boolean] Enable the original feature to open shulkerboxes by rightclicking into the air while holding them? (Recommended)
enable_rightclick_open: true # [Boolean] Enable the 2.0 feature to open shulkerboxes by rightclicking them inside the inventory? (Recommended)
rightclick_requires_permission: false # Right-click feature requires permissions? (Not recommended)

# Since 2.7.0 Better Shulker Boxes automatically recollects server information. This is with the only purpose of helping development.
# The data sent is completely anonymous, and it does not include compromising information.
# The data recollected is limited to:
# Server statistics: Player amount, online mode, Minecraft version, software (spigot, sponge, etc).
# Hosting statistics: Number of cores of the CPU, system architecture, operating system, server location (by country) and java version.
# Plugin (BSB only) statistics: Plugin version, some configuration parameters.
# For more information about statistics visit https://bstats.org/

# Although this data helps development I understand concerns about privacy.
# If you choose not to participate on statistics set the following parameter to false.
enable_statistics: true
